language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.1.18
    - php: 7.2
    - php: 7.3

before_install:
  - composer self-update

install:
  - composer install
  - composer require satooshi/php-coveralls:~1.0@stable

before_script:
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml --colors

after_success:
  - sh -c 'php vendor/bin/coveralls -v'